export const skillsList = [
  // Technical/Professional Skills
  "Programming",
  "Data Analysis",
  "Web Development",
  "Mobile App Development",
  "Machine Learning",
  "Artificial Intelligence",
  "Database Management",
  "Networking",
  "Project Management",
  "Agile Methodology",
  "UI/UX Design",
  "Graphic Design",
  "Video Editing",
  "Content Writing",
  "Copywriting",
  "Digital Marketing",
  "SEO",
  "Social Media Management",
  "Financial Analysis",
  "Statistical Analysis",
  "Public Speaking",
  "Leadership",
  "Time Management",
  "Problem Solving",
  "Critical Thinking",
  "Decision Making",
  "Negotiation",

  // Personal Development Skills
  "Emotional Intelligence",
  "Self-Discipline",
  "Resilience",
  "Adaptability",
  "Stress Management",
  "Assertiveness",
  "Mindfulness",
  "Effective Communication",
  "Active Listening",
  "Empathy",

  // Creative Skills
  "Drawing",
  "Painting",
  "Sculpting",
  "Photography",
  "Music Production",
  "Singing",
  "Dancing",
  "Writing Poetry",
  "Creative Writing",
  "Cooking",
  "Baking",
  "Crafting",
  "Interior Design",
  "Fashion Design",
  "Acting",
  "Storytelling",

  // Language Skills
  "Foreign Language Proficiency",
  "Translation",
  "Interpreting",

  // Sports and Physical Skills
  "Swimming",
  "Running",
  "Yoga",
  "Martial Arts",
  "Cycling",
  "Strength Training",
  "Dancing",
  "Skiing",

  // Miscellaneous Skills
  "Problem Solving",
  "First Aid/CPR",
  "Car Maintenance",
  "Gardening",
  "Home Repairs",
  "Negotiation",
  "Sales",
  "Customer Service",
  "Public Speaking",
  "Networking",
  "Time Management",
  "Leadership",
];
